name: 7nord
favicon: null
layout_spectrum: 0.971263972343877
typography_spectrum: 0.7958310628309846
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3288277026731521
  lightness: 0.875925233354792
  saturation: 0.6961175047326833
  rhythmicContrast: 0.18837179988622665
purpose: []
